CREATE TABLE CARD(
    ID SERIAL PRIMARY KEY,
    PAN VARCHAR(20) UNIQUE NOT NULL,
    PAR VARCHAR(128),
    CIRCUIT VARCHAR(5) NOT NULL,
    TOKENS VARCHAR(800)
);

CREATE TABLE TOKEN_BIN_RANGE(
    ID SERIAL PRIMARY KEY,
    CIRCUIT VARCHAR(20) NOT NULL,
    MIN_RANGE VARCHAR(50) UNIQUE NOT NULL,
    MAX_RANGE VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE CONFIG(
    ID SERIAL PRIMARY KEY,
    CONFIG_NAME VARCHAR(100) UNIQUE NOT NULL,
    CONFIG_VALUE VARCHAR(500) NOT NULL
);