microservice-chart:
  namespace: "shared"
  nameOverride: ""
  fullnameOverride: ""
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopaucommonacr.azurecr.io/tkmmockcircuit
        tag: "latest"
        pullPolicy: Always
    envConfig:
      CIRCUIT_MOCK_DB_USERNAME: ""
      SERVER_PORT: "true"
    envSecret:
      CIRCUIT_MOCK_DB_PASSWORD: tkm-db-password
  image:
    repository: pagopaucommonacr.azurecr.io/tkmmockcircuit
    tag: "0.1.1"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weuuat.ecommerce.internal.uat.platform.pagopa.it"
    path: /tkm/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "384Mi"
      cpu: "200m"
    limits:
      memory: "384Mi"
      cpu: "200m"
  autoscaling:
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: 26abc801-0d8f-4a6e-ac5f-8e81bcc09112
          resourceGroupName: pagopa-u-shared-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/pagopa-u-shared-kv
          metricName: ServiceApiHit
          # metricNamespace: Microsoft.KeyVault/vaults
          # metricFilter: namespace eq 'default'
          # metricAggregationInterval: "-1:1:0"
          metricAggregationType: Count
          targetValue: "30"
    envConfig:
      CIRCUIT_MOCK_DB_USERNAME: ""
      SERVER_PORT: "true"
    envSecret:
      CIRCUIT_MOCK_DB_PASSWORD: tkm-db-password
  keyvault:
    name: "pagopa-u-shared-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d" # TODO: udpdate with correct TENANTID
  nodeSelector: {}
  tolerations: []
  affinity: {}