microservice-chart:
  namespace: "shared"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/tkmmockcircuit
    tag: "1.0.5-7"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weuuat.ecommerce.internal.dev.platform.pagopa.it"
    path: /tkm/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "384Mi"
      cpu: "200m"
    limits:
      memory: "384Mi"
      cpu: "200m"
  autoscaling:
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: bbe47ad4-08b3-4925-94c5-1278e5819b86
          resourceGroupName: pagopa-u-shared-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/pagopa-u-shared-kv
          metricName: ServiceApiHit
          metricAggregationType: Count
          targetValue: "30"
  envConfig:
    CIRCUIT_MOCK_DB_USERNAME: ""
    SERVER_PORT: 8080
  envSecret:
    CIRCUIT_MOCK_DB_PASSWORD: tkm-db-password
    VISA_CERTIFICATE: tkm-visa-certificate
    VISA_PRIVATE_KEY: tkm-visa-private-key
  keyvault:
    name: "pagopa-u-shared-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
